export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const FAVOURITE_CONTACT = "FAVOURITE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const TAB_CHANGE = "TAB_CHANGE";
